### ISSUE TITLE
hastexo not showing any screen using Google cloud

### ISSUE THREAD

**Issue by nikhilrayaprolu** [hastexo/hastexo-xblock#103]
Hello, 
I am trying to use hastexo xblock with google cloud, but I am facing this single screen all the time.
![image](https://user-images.githubusercontent.com/15216503/64336062-bad77700-cff9-11e9-99c6-9ea6529e4e9c.png)

I installed guacamole by using dockerfile provided in the guacamole folder of this repo. If there is any error in my template or any config, how could I know?

**Comment by arbrandes** [comment]
@nikhilrayaprolu, this could be due to any number of problems.  Do you have access to the LMS logs for the edX instance where you deployed the XBLock?  Including the Celery LMS queue logs.  If you can post relevant sections, it will be easier for me to help you.

**Comment by fghaas** [comment]
Closing due to lack of further comment from reporter.
