### ISSUE TITLE
Upgrade from Cypress to Dogwood

### ISSUE THREAD

**Issue by edudemy** [hastexo/hastexo-xblock#14]
Hi Hastexo Team,

Would it be possible to upgrade seamlessly from Cypress( https://github.com/hastexo/edx-configuration/tree/integration/cypress ) to Dogwood on an Openstack installation, since the hastexo contributions (heat-templates, xblock) are targeted at Cypress release.

http://edx.readthedocs.org/projects/open-edx-icr/en/dogwood/dogwood.html#upgrading-from-cypress-to-dogwood 

Thanks.

**Comment by fghaas** [comment]
@edudemy Our own platform at https://academy.hastexo.com is already running on Dogwood. Are you running our XBlock on Cypress? Or are you planning to add it to a new Dogwood installation?

**Comment by edudemy** [comment]
@fghaas Planning on a new Dogwood installation, but also open to migrating from Cypress, if a clear path exists.

**Comment by fghaas** [comment]
Should have no issues with a direct-to-Dogwood installation. Tagging @arbrandes here as he may have other input to pitch in.

**Comment by edudemy** [comment]
@fghaas Would replacing Cypress with Dogwood in the heat-templates suffice? Or are there specific cusotmizations for the Dogwood Openstack installation. Thanks.

**Comment by arbrandes** [comment]
@edudemy, I just realized our README is a tad obsolete.  Give me a few moments as I update it, so I can point you to something you can actually use. :)

**Comment by arbrandes** [comment]
@edudemy, here you go:

https://github.com/hastexo/hastexo-xblock#deployment

The Heat templates in the `hastexo/master/base` branch of [our fork](https://github.com/hastexo/edx-configuration/tree/hastexo/master/base) (which is what I recommend you use for Dogwood and upwards) of edx-configuration have been updated recently as well.

The sample Heat template for use in the courseware has also been updated in this repository.  I highly recommend you base yourself on it to start with.

**Comment by arbrandes** [comment]
Also, please take a look at this (it was also updated):

https://github.com/hastexo/edx-configuration/tree/hastexo/master/base/heat-templates#single-node-with-the-hastexo-xblock

There's an equivalent set of instructions to deploy the XBlock on a multi-node environment, further down the page.
