### ISSUE TITLE
i want to integrte VPL server in open edx . can any one help 

### ISSUE THREAD

**Issue by apssdc-ghouse** [hastexo/hastexo-xblock#18]
i want to integrte VPL server in open edx . can any one help

**Comment by fghaas** [comment]
You do realize that VPL Server is specific to Moodle, right? Are you looking to implement something *similar* to VPL, in Open edX?

**Comment by apssdc-ghouse** [comment]
Thanks for replay,

yes am looking for the similer  to VPL, in Open edX. Do you have any
solution.

**Comment by fghaas** [comment]
All I know is that VPL is specific to Moodle; I have never used nor deployed it. I think you'll need to figure out for yourself whether this XBlock, or any other available in Open edX, does what you need it to do. I'm afraid I'm not really able to help here further.
