### ISSUE TITLE
Stacks should check for actual, not last-reported, state when resuming

### ISSUE THREAD

**Issue by fghaas** [hastexo/hastexo-xblock#51]
If I understand correctly, then the current behavior of suspend/resume is as follows.

# Suspend/resume *enabled*

- Labs spin up → `CREATE_COMPLETE`
- Learner is inactive for some time, labs suspend → `SUSPEND_COMPLETE`
- Learner goes back to lab, labs resume → `RESUME_COMPLETE`
- Learner hits BRS, stack resets → `DELETE_COMPLETE` → `CREATE_COMPLETE`

# Suspend/resume *disabled*

- Labs spin up → `CREATE_COMPLETE`
- Stacks never hit the `SUSPEND_COMPLETE` or `RESUME_COMPLETE` status
- Learner hits BRS, stack resets → `DELETE_COMPLETE` → `CREATE_COMPLETE`

# Suspend/resume *enabled* at first, then provider configuration change

Now if we're dealing with a provider that first has suspend _enabled_, and then subsequently _disabled_, here's what happens:

- Labs spin up → `CREATE_COMPLETE`
- Learner is inactive for some time, labs suspend → `SUSPEND_COMPLETE`
- *Configuration change*
- Learner goes back to lab, **lab does not resume**.

I understand that this is because when suspend is disabled, so is resume — in other words, if the xblock never suspends, then it never assumes that a stack it manages could be suspended at all.

* * *

I think the current behavior is non-intuitive, not only in the face of a configuration change, but also in a scenario where automatic stack suspension is disabled, but a stack may have been *manually* suspended by an operator. I'd suggest that even if suspend is disabled, the Xblock should check for a stack's `SUSPEND_COMPLETE` stack and resume as needed (and then just never automatically re-suspend).

**Comment by fghaas** [comment]
Let me know what you think of this, @arbrandes.

**Comment by arbrandes** [comment]
I disagree.  Checking for actual status every time will make things too
slow.  If the operator changed things manually, I say it is on him to get
them in a state compatible with what the XBlock would expect.  Otherwise,
we're penalizing all the time for a corner case that basically should never
happen anyway.

**Comment by fghaas** [comment]
I can follow that reasoning, though I wouldn't say that changing the configuration while managed stacks already exist isn't a "can't happen" case — anything that is configurable should be expected to change.

So basically, the thinking is "if you disable suspend on a provider where it was previously enabled, you must manually resume all suspended stacks". Is that accurate?

**Comment by arbrandes** [comment]
Yes, that's what I'm arguing for - though I'm not saying it's ideal.

"Ideal", IMHO, would be checking for stack status without adding a
significant delay to the 80% use case.  For instance, it's theoretically
possible to handle an SSH connection error such as the one displayed here
by _then_ checking if the stack is unexpectedly suspended.  (In practice,
I'd just reset the last reported state and start from scratch.)

Gateone's not very wieldy, but it would probably be doable.  And it's
reasonably safe to assume that the Guacamole JS API offers a "connection
error" event we can use.

The only question is whether to tackle this now, or after a Guacamole port.

**Comment by fghaas** [comment]
Yeah, that would be an EAFP approach — try connecting, and only if that fails, resume, and only if that fails (because the stack does not exist yet), create. Did I get that right?

**Comment by arbrandes** [comment]
Exactly!

**Comment by fghaas** [comment]
One practical concern with that, though. When the connection fails because the stack is down, it doesn't produce a TCP RST, it just times out. We can't wait for that timeout forever, because it's bad UX, but we also can't make it too short, because it would produce false positives in flakey/jittery network environments.

**Comment by fghaas** [comment]
Closing long-stale issue. We no longer have this problem, though I'm presently unable to dig up where exactly it was fixed.
