### ISSUE TITLE
Copy-paste: only Ctrl-Shift-V seems to work (in some configurations?)

### ISSUE THREAD

**Issue by fghaas** [hastexo/hastexo-xblock#56]
Ubuntu 17.10, Chromium 63.0.3239.84 on Gnome 3 with Wayland. 

9e8ccb584a3261f9ec79b5e538c7f32bb7b9adbd seems to indicate that all of Ctrl-V, Shift-Insert, or Ctrl-Shift-V should work to paste into the terminal.

In my current setup, Ctrl-V seems to insert `^V` into the terminal. Shift-Insert gets rendered as `^[[2~`. Ctrl-Shift-V does actually paste the contents of my clipboard.

**Comment by arbrandes** [comment]
Only Ctrl-Shift-V is supposed to work, as things stand.  Reading the
Javascript may be misleading because it does not take into account what
key(s) the server-side terminal emulator expects (and it only expects
Ctrl-Shift-V, for SSH).

**Comment by fghaas** [comment]
Um, I didn't read the JavaScript, I read the commit message. :)

```
Implement pasting

This implements synchronous pasting into the remote VM.  Following a
paste shortcut (ctrl-v, shift-insert, or ctrl-shift-v), the contents of
the local clipboard are sent to the remote clipboard, after which the
key combination is also sent.

Currently only works in Chrome.
```

**Comment by fghaas** [comment]
We can close this, as there *is* a way to paste into the Guacamole window for non-Chrome browsers. In Firefox:

1. Copy text into local clipboard on the client.
2. Left-click into the Guacamole terminal.
3. Type `Ctrl-V`.
4. Right-click or middle-click into the terminal.
