### ISSUE TITLE
Reaper should clear stack provider after successful deletion

### ISSUE THREAD

**Issue by arbrandes** [hastexo/hastexo-xblock#92]
Currently, the reaper doesn't clear the provider column in `hastexo_stack` when a stack is successfully deleted.  If a owner of a deleted stack comes back before the course run ends, the XBlock will always try to recreate the stack in the previous provider.  This may not be intended behavior if there are multiple configured providers.  Furthermore, if the course's provider configuration was changed in the meantime to remove the previous provider, this may lead to a launch error.

**Comment by fghaas** [comment]
This was fixed as part of the reaper refactoring in 468e31287043b9bac783a1b9f08d25abef156c22 (#97). Since then, [successful deletion does clear the provider](https://github.com/hastexo/hastexo-xblock/blob/468e31287043b9bac783a1b9f08d25abef156c22/hastexo/tasks.py#L626).
